# BathGuard configuration - ENHANCED WITH SHOWER-AWARE DETECTION
backend:
  type: "movenet_tflite"
  model_path: "models/movenet_singlepose_lightning.tflite"
  num_threads: 3

camera:
  enabled: true
  index: 0
  width: 640
  height: 480
  fps: 15

risk:
  angle_threshold_deg: 50          # Reasonable trigger point for potential risk
  drop_threshold: 0.15             # Moderate sensitivity
  drop_window_s: 1.0               # Standard window
  immobile_window_s: 10.0          # Base immobility threshold (10 seconds)
  immobile_motion_eps: 0.05        # Base movement tolerance
  soft_immobility_s: 30.0          # Soft alert after 30 seconds
  hard_immobility_s: 60.0          # Emergency alert after 60 seconds
  cooldown_s: 600                  # 10 minute cooldown
  # Enhanced shower-aware detection
  movement_tolerance_low_angle: 0.12   # More lenient when bent (shower activities)
  movement_tolerance_high_angle: 0.05  # Stricter when upright
  shower_mode_enabled: true
  shower_start_hour: 6             # Shower hours start
  shower_end_hour: 22              # Shower hours end
  shower_duration_multiplier: 4.0  # 4x longer thresholds during shower hours

telegram:
  type: "telegram"