# DuruOn configuration - Bathroom emergency monitoring with PIR activation and LED indicators
backend:
  type: "movenet_tflite"
  model_path: "models/movenet_singlepose_lightning.tflite"
  num_threads: 3

camera:
  enabled: true
  index: 0
  width: 640
  height: 480
  fps: 15

risk:
  angle_threshold_deg: 55          # Slightly more permissive angle for horizontal/low posture
  drop_threshold: 0.10             # Require a bit larger vertical change (reduce false drops)
  drop_window_s: 0.9               # Short window for sudden movement
  immobile_window_s: 10.0          # Window for averaging motion
  immobile_motion_eps: 0.05        # Base movement tolerance
  soft_immobility_s: 30.0          # Soft alert after 30s immobile (no detected fall)
  hard_immobility_s: 90.0          # Fallback hard escalation after prolonged immobility
  fast_fall_immobility_s: 12.0     # Fast path: immobility duration needed AFTER a detected sudden drop to confirm hard_fall
  cooldown_s: 120                  # 2 minute cooldown to reduce alert spam
  # Enhanced shower-aware detection
  movement_tolerance_low_angle: 0.50   # Very permissive tolerance to ensure alerts trigger
  movement_tolerance_high_angle: 0.05  # Stricter when upright
  shower_mode_enabled: true
  shower_start_hour: 6             # Shower hours start
  shower_end_hour: 22              # Shower hours end
  shower_duration_multiplier: 4.0  # 4x longer thresholds during shower hours

# PIR Sensor Activation System
pir_activation:
  enabled: true                    # Enable PIR sensor activation
  pir_pin: 24                      # GPIO pin number (BCM numbering)
  debounce_time: 2.0               # Minimum seconds between PIR triggers
  activation_grace_period: 0.5    # Delay before full monitoring starts (seconds)
  auto_sleep_timeout: 300.0       # Return to idle after 5 minutes of no motion

# NEW: LED Status Indicators
led_indicators:
  enabled: true                    # Enable LED status indicators
  green_pin: 18                    # System status LED (GPIO pin)
  blue_pin: 23                     # PIR activity LED (GPIO pin)
  red_pin: 25                      # Alert status LED (GPIO pin)

telegram:
  type: "telegram"

# Alerting & reliability enhancements
alerting:
  stop_button: true              # Include STOP button in alert inline keyboard
  repeat_unacked_after_s: 180    # Resend alert if no ACK after this many seconds
  max_repeats: 3                 # Maximum additional repeats (0 = no repeats)
  heartbeat:
    enabled: true                # Send periodic heartbeat message
    interval_s: 86400            # Every 24h
  log_rotate_kb: 64              # Rotate alert log after ~64 KB
  log_keep: 5                    # Keep last 5 rotated logs
  adaptive_soft_multiplier: 1.0  # Reserved for future adaptive tuning
  adaptive_hard_multiplier: 1.0  # Reserved for future adaptive tuning