# DuruOn configuration - Bathroom emergency monitoring with PIR activation and LED indicators
backend:
  type: "movenet_tflite"
  model_path: "models/movenet_singlepose_lightning.tflite"
  num_threads: 3

camera:
  enabled: true
  index: 0
  width: 640
  height: 480
  fps: 15

risk:
  angle_threshold_deg: 50          # Practical threshold for bent-over/fall detection (50° from vertical)
  drop_threshold: 0.05             # Very sensitive vertical drop threshold for slips  
  drop_window_s: 3.0               # Longer window to accumulate enough samples for detection  
  angle_change_threshold: 20.0     # Lower angle change threshold to catch gradual slips
  position_change_threshold: 0.12  # More sensitive position change threshold
  immobile_window_s: 10.0          # Window for averaging motion
  immobile_motion_eps: 0.05        # Normal movement tolerance for motion detection
  soft_immobility_s: 15.0          # Alert after 15s immobile for angles <50°
  hard_immobility_s: 45.0          # Hard escalation after 45s immobility
  fast_fall_immobility_s: 8.0      # Faster confirmation after detected fall
  cooldown_s: 30                   # 30 second cooldown to allow testing
  # Enhanced shower-aware detection
  movement_tolerance_low_angle: 0.12   # Normal tolerance for low angles
  movement_tolerance_high_angle: 0.05  # Strict tolerance when upright
  shower_mode_enabled: true
  shower_start_hour: 6             # Shower hours start
  shower_end_hour: 22              # Shower hours end
  shower_duration_multiplier: 4.0  # 4x longer thresholds during shower hours

# PIR Sensor Activation System
pir_activation:
  enabled: true                    # Enable PIR sensor activation
  pir_pin: 24                      # GPIO pin number (BCM numbering)
  debounce_time: 2.0               # Minimum seconds between PIR triggers
  activation_grace_period: 0.5    # Delay before full monitoring starts (seconds)
  auto_sleep_timeout: 300.0       # Return to idle after 5 minutes of no motion

# NEW: LED Status Indicators
led_indicators:
  enabled: true                    # Enable LED status indicators
  green_pin: 18                    # System status LED (GPIO pin)
  blue_pin: 23                     # PIR activity LED (GPIO pin)
  red_pin: 25                      # Alert status LED (GPIO pin)

telegram:
  type: "telegram"

# Alerting & reliability enhancements
alerting:
  stop_button: true              # Include STOP button in alert inline keyboard
  repeat_unacked_after_s: 180    # Resend alert if no ACK after this many seconds
  max_repeats: 3                 # Maximum additional repeats (0 = no repeats)
  heartbeat:
    enabled: true                # Send periodic heartbeat message
    interval_s: 86400            # Every 24h
  log_rotate_kb: 64              # Rotate alert log after ~64 KB
  log_keep: 5                    # Keep last 5 rotated logs
  adaptive_soft_multiplier: 1.0  # Reserved for future adaptive tuning
  adaptive_hard_multiplier: 1.0  # Reserved for future adaptive tuning