# BathGuard configuration - TEST MODE (more sensitive)
backend:
  type: "movenet_tflite"
  model_path: "models/movenet_singlepose_lightning.tflite"
  num_threads: 3

camera:
  enabled: true
  index: 0
  width: 640
  height: 480
  fps: 15

risk:
  angle_threshold_deg: 75          # More lenient (was 65)
  drop_threshold: 0.15             # More sensitive (was 0.25)
  drop_window_s: 1.0               # Longer window (was 0.7)
  immobile_window_s: 2.0           # Shorter wait (was 4.0)
  immobile_motion_eps: 0.02        # More sensitive (was 0.01)
  soft_immobility_s: 60            # Shorter wait (was 120)
  cooldown_s: 30                   # Shorter cooldown for testing (was 300)

telegram:
  type: "telegram"